name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.uv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install --system .
          uv pip install --system ".[tests]"

      - name: Run Ruff
        run: |
          ruff check . --fix

      - name: Build package
        run: |
          uv run build

      - name: Run tests
        run: |
          uv run pytest 